version: '3.8'

networks:
  KadancevV-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      KadancevV-my-netology-hw:
        ipv4_address: 10.5.0.10
    restart: unless-stopped
    ports:
      - "9100:9100"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: KadancevV-netology-pushgateway
    networks:
      KadancevV-my-netology-hw:
        ipv4_address: 10.5.0.20
    restart: unless-stopped
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    container_name: KadancevV-netology-prometheus
    networks:
      KadancevV-my-netology-hw:
        ipv4_address: 10.5.0.30
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
      - pushgateway

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    networks:
      KadancevV-my-netology-hw:
        ipv4_address: 10.5.0.40
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: KadancevV-netology-grafana
    networks:
      KadancevV-my-netology-hw:
        ipv4_address: 10.5.0.50
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "80:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    volumes:
      - grafana_data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/custom.ini
    depends_on:
      - prometheus
